AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create all endpoints

Parameters:
  ApiGatewayStack:
    Type: String
    Description: stack name
  Route53DNSStack:
    Type: String
    Description: stack name

Mappings:
  Resources:
    Product:
      ResourcePath: "products"
    Inventory:
      ResourcePath: "inventories"
    Promotion:
      ResourcePath: "promotion"
      PromotionCodeResourcePath: "codes"
      PromotionRuleResourcePath: "rules"
      ApplyPromotionResourcePath: "apply"
    Cart:
      ResourcePath: "carts"
      PayCartResourcePath: "pay"
      SubmitCartResourcePath: "submit"
    Order:
      ResourcePath: "orders"

Resources:
  ###############################################
  # API Gateway Resources
  ###############################################

  ProductResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayRootResourceId"
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Product, ResourcePath]

  InventoryResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayRootResourceId"
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Inventory, ResourcePath]

  PromotionResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayRootResourceId"
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Promotion, ResourcePath]

  PromotionCodeResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref PromotionResource
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Promotion, PromotionCodeResourcePath]

  PromotionRuleResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref PromotionResource
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Promotion, PromotionRuleResourcePath]

  ApplyPromotionResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref PromotionResource
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Promotion, ApplyPromotionResourcePath]

  CartResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayRootResourceId"
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Cart, ResourcePath]

  PayCartResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref CartResource
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Cart, PayCartResourcePath]

  SubmitCartResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref CartResource
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Cart, SubmitCartResourcePath]

  OrderResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayRootResourceId"
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      PathPart:
        Fn::FindInMap: [Resources, Order, ResourcePath]

Outputs:
  ProductResourceId:
    Value: !GetAtt ProductResource.ResourceId
    Description: Id of Product resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ProductResourceId"
  InventoryResourceId:
    Value: !GetAtt InventoryResource.ResourceId
    Description: Id of Inventory resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-InventoryResourceId"
  PromotionResourceId:
    Value: !GetAtt PromotionResource.ResourceId
    Description: Id of Promotion resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PromotionResourceId"
  PromotionCodeResourceId:
    Value: !GetAtt PromotionCodeResource.ResourceId
    Description: Id of PromotionCode resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PromotionCodeResourceId"
  PromotionRuleResourceId:
    Value: !GetAtt PromotionRuleResource.ResourceId
    Description: Id of PromotionRule resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PromotionRuleResourceId"
  ApplyPromotionResourceId:
    Value: !GetAtt ApplyPromotionResource.ResourceId
    Description: Id of ApplyPromotion resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ApplyPromotionResourceId"
  CartResourceId:
    Value: !GetAtt CartResource.ResourceId
    Description: Id of Cart resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CartResourceId"
  PayCartResourceId:
    Value: !GetAtt PayCartResource.ResourceId
    Description: Id of PayCart resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PayCartResourceId"
  SubmitCartResourceId:
    Value: !GetAtt SubmitCartResource.ResourceId
    Description: Id of SubmitCart resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SubmitCartResourceId"
  OrderResourceId:
    Value: !GetAtt OrderResource.ResourceId
    Description: Id of Order resource
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-OrderResourceId"
