AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create add-product-function

Parameters:
  ApiGatewayStack:
    Type: String
    Description: stack name
  EndpointsStack:
    Type: String
    Description: stack name
  AlbStack:
    Type: String
    Description: "Name of the ALB Stack"

Resources:
  # https://docs.aws.amazon.com/apigateway/latest/developerguide/setup-http-integrations.html

  GetProfileMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      ResourceId:
        Fn::ImportValue: !Sub "${EndpointsStack}-ProfileResourceId"
      HttpMethod: GET
      AuthorizationType: "COGNITO_USER_POOLS"
      AuthorizerId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayAuthorizerId"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 400
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 404
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 500
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri:
          Fn::Sub:
            - "http://${AlbDnsName}/core/api/profile"
            - AlbDnsName:
                Fn::ImportValue:
                  Fn::Sub: "${AlbStack}-EcsALBDNSName"
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: ""
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 400
            SelectionPattern: "400"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 404
            SelectionPattern: "404"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 500
            SelectionPattern: "500"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"

  PostUpdateProfileMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayId"
      ResourceId:
        Fn::ImportValue: !Sub "${EndpointsStack}-ProfileResourceId"
      HttpMethod: POST
      AuthorizationType: "COGNITO_USER_POOLS"
      AuthorizerId:
        Fn::ImportValue: !Sub "${ApiGatewayStack}-ApiGatewayAuthorizerId"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 400
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 404
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: 500
          ResponseModels:
            application/json: "Error"
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - "http://${AlbDnsName}/core/api/profile"
            - AlbDnsName:
                Fn::ImportValue:
                  Fn::Sub: "${AlbStack}-EcsALBDNSName"
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: ""
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 400
            SelectionPattern: "400"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 404
            SelectionPattern: "404"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 500
            SelectionPattern: "500"
            ResponseTemplates:
              application/json: $input.json('$')
            ResponseParameters:
              method.response.header.Content-Type: "'application/json'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
