AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for creating secrets SSM Paramter"

Parameters:
  StripeSecretKeyName:
    Type: String
    Description: "Name of the secret"
    Default: "/shop/stripe/secretKey"
  StripeSecretKeyValue:
    Type: String
    NoEcho: true
    Description: "Value of the secret"
  StripeSecretHookKeyName:
    Type: String
    Description: "Name of the secret"
    Default: "/shop/stripe/webhookSecret"
  StripeSecretHookValue:
    Type: String
    NoEcho: true
    Description: "Value of the secret"

Resources:
  StripeSecretKeyParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref StripeSecretKeyName
      Type: "String"
      Value: !Ref StripeSecretKeyValue
      Description: "Stripe Secret Key"

  StripeSecretHookParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref StripeSecretHookKeyName
      Type: "String"
      Value: !Ref StripeSecretHookValue
      Description: "Stripe Secret Hook"
